version: '3.4'

services:
  srt2text:
    image: srt2text
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 srt2text.py "]
    ports:
      - 5678:5678
